# Generated by Django 4.1 on 2022-08-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_bookauthors_booklanguage_bookshelf_bookshelves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dowload_count',
            new_name='download_count',
        ),
    ]
