# Generated by Django 4.1 on 2022-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookauthors_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='mimme_type',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
